# **MATRIX**

- Vectors Are also Type of  

In [ ]:
Matrix_1=np.asarray([[2,3],[4,5]])
print(Matrix_1)

[[2 3]
 [4 5]]


Creating Matrices With Random Value

In [ ]:
#random.rand generates floating values
Matrix_2=np.random.rand(3,3)
print(Matrix_2)

[[0.65205209 0.715908   0.86169436]
 [0.79578899 0.52182434 0.47193563]
 [0.01222254 0.62771035 0.30526152]]


In [ ]:
# random.randint generates integer values
Matrix_3=np.random.randint(100, size=(3,3))
print(Matrix_3)

[[40 60 99]
 [60 69 38]
 [50 20 27]]


Matrix With All Values as 1

In [ ]:
# dtype argument is optional
Matrix_4=np.ones((3,3), dtype=int) # By Default dtype is floats
print(Matrix_4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Null Matrix / Zero Matrix

In [ ]:

Matrix_5=np.zeros((3,3))
print(Matrix_5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Diagonal Matrix

In [ ]:
Matrix_6=np.diag([1,2,3,4])
print(Matrix_6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Identity Matrix

In [ ]:
Matrix_7=np.identity(3)
print(Matrix_7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose Of Matrix

In [ ]:
# Creating a Matrix of Random Integer Values
Matrix_8=np.random.randint(100, size=(3,4))
print(Matrix_8)

[[47 20 11 29]
 [41 50 18 24]
 [70 38 46 89]]


In [ ]:
# Now creating transpose of Matrix
Transpose_of_Matrix_8=np.transpose(Matrix_8)
print(Transpose_of_Matrix_8)


[[47 41 70]
 [20 50 38]
 [11 18 46]
 [29 24 89]]


**MATRIX OPERATIONS**


MATRIX ADDITION
- Matrices Should Have The Same Number Of Rows & Column
- Elementwise Addition

In [ ]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
C=A+B
print(C)

[[ 6  8]
 [10 12]]


MATRIX SUBTRACTION
- Matrices Should Have The Same Number Of Rows & Column
- Elementwise Subtraction

In [ ]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
C=A-B
print(C)

[[-4 -4]
 [-4 -4]]


MATRIX MULTIPLICATION BY SCALAR

- Elementwise Multiplication

In [ ]:
B=np.array([[5,6],[7,8]])
C=2*B
print(C)

[[10 12]
 [14 16]]


MULTIPLICATION OF 2 MATRIX

- Number of columns of 1st Matrix Must be Equal To Number of Rows if 2nd Matrix

- The Resultant Matrix will have Same Number Of Rows as The 1st Matrix & The Same Number Of Columns as The 2nd Matrix

In [ ]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
C=A*B
print(C)

[[ 5 12]
 [21 32]]
